apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../../bases/uganda-service-hub
replicas:
- count: 1
  name: uganda-service-hub-dev
patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: uganda-service-hub-dev
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: uganda-service-hub-dev
  target:
    group: apps
    kind: Deployment
    name: uganda-service-hub
    version: v1
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: uganda-service-hub-homelab-dev
  target:
    kind: Service
    name: uganda-service-hub
    version: v1
- path: version.yaml


