apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  labels:
    app.kubernetes.io/name: taskflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taskflow-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taskflow-frontend
    spec:
      containers:
        - name: taskflow-frontend
          image: ghcr.io/markbenjaminkatamba/taskflow-frontend:latest
          ports:
            - containerPort: 8080


