apiVersion: v1
kind: Service
metadata:
  name: dockerfile-generator-frontend
spec:
  selector:
    app.kubernetes.io/name: dockerfile-generator-frontend
  ports:
    - port: 80
      targetPort: 3000