apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../../bases/taskflow-frontend
- ../ghcr-secret.yaml
replicas:
- count: 1
  name: taskflow-frontend-dev
patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: taskflow-frontend-dev
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: taskflow-frontend-dev
  target:
    group: apps
    kind: Deployment
    name: taskflow-frontend
    version: v1
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: taskflow-frontend-dev
  target:
    kind: Service
    name: taskflow-frontend
    version: v1
- path: version.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: ghcr-cred
  target:
    group: apps
    kind: Deployment
    name: taskflow-frontend
    version: v1


