apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -homelab-dev
resources:
- ../../../bases/sukuulu
replicas:
- count: 1
  name: sukuulu-homelab-dev
patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: sukuulu-homelab-dev
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: sukuulu-homelab-dev
  target:
    group: apps
    kind: Deployment
    name: sukuulu
    version: v1
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: sukuulu-homelab-dev
  target:
    kind: Service
    name: sukuulu
    version: v1
- path: version.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: ghcr-cred
  target:
    group: apps
    kind: Deployment
    name: sukuulu
    version: v1


