# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerfile-generator-backend
  labels:
    app: dockerfile-generator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerfile-generator-backend
  template:
    metadata:
      labels:
        app: dockerfile-generator-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/markbenjaminkatamba/dockerfile-generator-backend-dev:latest
          ports:
            - containerPort: 8000

