---
apiVersion: v1
kind: Service
metadata:
  name: dockerfile-generator-backend
spec:
  selector:
    app.kubernetes.io/name: dockerfile-generator-backend
  ports:
    - port: 80
      targetPort: 8000
