apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../../bases/dockerfile-generator-backend
replicas:
- count: 1
  name: dockerfile-generator-backend-dev
patches:
- patch: "- op: replace\n  path: /spec/template/metadata/labels/app.kubernetes.io~1name\n
    \ value: dockerfile-generator-backend-dev\n- op: replace\n  path: /spec/selector/matchLabels/app.kubernetes.io~1name\n
    \ value: dockerfile-generator-backend-dev  "
  target:
    group: apps
    kind: Deployment
    name: dockerfile-generator-backend
    version: v1
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: dockerfile-generator-backend-dev
  target:
    kind: Service
    name: dockerfile-generator-backend
    version: v1
- path: version.yaml
