apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
  - ../../bases/dockerfile-generator-frontend

replicas:
- count: 1
  name: dockerfile-generator-frontend-dev

patchesStrategicMerge:
  - version.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: dockerfile-generator-frontend
  patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
- target:
    version: v1
    kind: Service
    name: dockerfile-generator-frontend
  patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
