apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../bases/dockerfile-generator-frontend
replicas:
- count: 1
  name: dockerfile-generator-frontend-dev
patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
  target:
    group: apps
    kind: Deployment
    name: dockerfile-generator-frontend
    version: v1
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: dockerfile-generator-frontend-dev
  target:
    kind: Service
    name: dockerfile-generator-frontend
    version: v1
- path: version.yaml
