apiVersion: apps/v1
kind: Deployment
metadata:
  name: uganda-service-hub
  labels:
    app.kubernetes.io/name: uganda-service-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uganda-service-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uganda-service-hub
    spec:
      containers:
        - name: uganda-service-hub
          image: ghcr.io/you/app:latest
          ports:
            - containerPort: 8080


